mappings:
  WebPortfolioPageTimeLine: Sunnysideup\WebPortfolio\WebPortfolioPageTimeLine
  WebPortfolioPageTimeLine_Controller: Sunnysideup\WebPortfolio\WebPortfolioPageTimeLine_Controller
  WebPortfolioPage: Sunnysideup\WebPortfolio\WebPortfolioPage
  WebPortfolioPage_Controller: Sunnysideup\WebPortfolio\WebPortfolioPage_Controller
  WebPortfolioItem: Sunnysideup\WebPortfolio\Dataobjects\WebPortfolioItem
  WebPortfolioWhatWeDidDescriptor: Sunnysideup\WebPortfolio\Dataobjects\WebPortfolioWhatWeDidDescriptor
  WebPortfolioAdmin: Sunnysideup\WebPortfolio\Dataobjects\WebPortfolioAdmin
  WebPortfolioAgent: Sunnysideup\WebPortfolio\Dataobjects\WebPortfolioAgent
