mappings:
  WebPortfolioPageTimeLine: Sunnysideup\WebPortfolio\WebPortfolioPageTimeLine
  WebPortfolioPageTimeLine_Controller: Sunnysideup\WebPortfolio\WebPortfolioPageTimeLine_Controller
  WebPortfolioPage: Sunnysideup\WebPortfolio\WebPortfolioPage
  WebPortfolioPage_Controller: Sunnysideup\WebPortfolio\WebPortfolioPage_Controller
  WebPortfolioItem: Sunnysideup\WebPortfolio\Models\WebPortfolioItem
  WebPortfolioWhatWeDidDescriptor: Sunnysideup\WebPortfolio\Models\WebPortfolioWhatWeDidDescriptor
  WebPortfolioAdmin: Sunnysideup\WebPortfolio\Models\WebPortfolioAdmin
  WebPortfolioAgent: Sunnysideup\WebPortfolio\Models\WebPortfolioAgent
